# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
fabric_version=0.116.0+1.21.1
loader_version=0.16.14

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 1.21:2024.07.28

# Compat
# https://modrinth.com/mod/jei/versions?g=1.21.1&l=fabric
jei_version = 19.21.0.246
# https://modrinth.com/mod/rei/versions?g=1.21.1&l=fabric
rei_version = 16.0.783
# architectury_version = 6.0.37
# https://modrinth.com/mod/emi/versions?g=1.21.1&l=fabric
emi_version = 1.1.18+1.21.1

# Forge Config Api Port
# https://github.com/Fuzss/forgeconfigapiport/tree/main
forge_config_api_port_version = 21.1.3

# Cloth Config
# https://modrinth.com/mod/cloth-config/versions?g=1.21.1&l=fabric
cloth_config_version=15.0.140

# Modmenu
# https://modrinth.com/mod/modmenu/versions?g=1.21.1&l=fabric
modmenu_version=11.0.2

# Sodium
# https://modrinth.com/mod/sodium/versions?g=1.21.1&l=fabric
sodium_version=mc1.21.1-0.6.0-fabric

# Jade
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
jade_version = 5706164

# Tom's Simple Storage Mod
# https://modrinth.com/mod/toms-storage/versions?g=1.21.1&l=fabric
toms_storage_version=1.21-2.2.3-fabric
cca_version=6.1.0

# CarryOn
carryon_version=2.2.3.3

# Simple Voice Chat
# https://modrinth.com/plugin/simple-voice-chat/versions?l=fabric&g=1.21.1
simple_voice_chat_version=fabric-1.21.1-2.5.26

# AudioPlayer
# https://modrinth.com/mod/audioplayer/versions?l=fabric&g=1.21.1
audioplayer_version=fabric-1.21.1-1.12.0
# https://modrinth.com/mod/admiral/versions?l=fabric&g=1.21.1
admiral_version=0.4.6+1.21.1+fabric

# OpenPartiesAndClaims
#
opac_version=6242911

# Yet Another World Protector
# https://www.curseforge.com/minecraft/mc-mods/yawp/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
yawp_version=6227072

# QuickBench
# https://www.curseforge.com/minecraft/mc-mods/quickbench/files/all?page=1&pageSize=20&version=1.21.1
quickbench_version=5784135

# Oritech
# https://www.curseforge.com/minecraft/mc-mods/oritech/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4
oritech_version=6558343
architectury_api_version=13.0.8
owo_version=0.12.15.4+1.21
geckolib_version=4.6.6
athena_version=4.0.0

# Blur+
# https://modrinth.com/mod/blur-plus/versions?g=1.21.1&l=fabric
blurplus_version=5.0.0-hotfix.1-fabric
midnightlib_version=1.6.9+1.21-fabric

# Carpetmod
carpet_version=1.4.147

# https://modrinth.com/mod/trinkets/versions?g=1.21.1&l=fabric
trinkets_version=3.10.0
# https://modrinth.com/mod/accessories/versions?g=1.21.1&l=fabric
accessories_version=1.1.0-beta.52+1.21.1
accessories_compat_version=OkGF8Kho

# What accessory mod provider to use ('trinkets' or 'accessories'.  if you change it, don't push it)
accessory_mod = accessories

# What recipe viewer to use ('emi', 'rei', or 'jei'. if you change it, don't push it)
recipe_viewer = emi